DOMAIN = "claw_assistant"

CONF_PRIMARY_AGENT = "primary_agent"
CONF_FALLBACK_AGENT = "fallback_agent"
CONF_SECONDARY_FALLBACK_AGENT = "secondary_fallback_agent"
CONF_CONVERSATION_MODE = "conversation_mode"
CONF_ERROR_RESPONSES = "error_responses"
CONF_ENABLE_AI_SUMMARY = "enable_ai_summary"
CONF_ENABLE_WEB_SEARCH = "enable_web_search"
CONF_ENABLE_STREAMING_EFFECT = "enable_streaming_effect"

CONVERSATION_MODE_NO_NAME = "no_name"
CONVERSATION_MODE_ADD_NAME = "add_name"
CONVERSATION_MODE_DETAILED = "detailed"

DEFAULT_CONVERSATION_MODE = CONVERSATION_MODE_ADD_NAME
DEFAULT_PRIMARY_AGENT = ""
DEFAULT_FALLBACK_AGENT = ""
DEFAULT_SECONDARY_FALLBACK_AGENT = None
